### ISSUE TITLE
Cannot find ActivityMainBinding

### ISSUE THREAD

**Issue by ttojiyev** [velmurugan-murugesan/Android-Example#6]
![image](https://user-images.githubusercontent.com/23132933/126044414-59f6b7fd-7b5d-4da0-9705-1f4d0dfc9f87.png)

Cannot find this ActivityMainBinding or it's package. Could you help me

**Comment by velmurugan-murugesan** [comment]
you need to enable viewBinding in gradle file to auto-generate this

**Comment by Rahul-kumar1997** [comment]
Cannot find this ActivityMovieBinding. Could you help me

<img width="645" alt="Screenshot 2021-08-06 at 11 07 24 AM" src="https://user-images.githubusercontent.com/64708181/128461896-6c95760d-3cdf-449c-825e-b49be51e08fc.png">

**Comment by velmurugan-murugesan** [comment]
AdapterMovieBinding is the auto-generated file for the adapter_movie.xml. you need to enable viewBinding in your gradle file. please check https://developer.android.com/topic/libraries/view-binding

**Comment by Rahul-kumar1997** [comment]
i already enable
<img width="246" alt="Screenshot 2021-08-06 at 11 35 24 AM" src="https://user-images.githubusercontent.com/64708181/128463942-abb01900-4008-4a3a-932a-dc5e905a3254.png">

**Comment by velmurugan-murugesan** [comment]
Try to rebuild the project. It's an auto-generated class. make sure that no error on the layout file.
